name: Test, lint, and build libraries

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint:ci

      - name: Test
        run: npm run test:ci

      - name: Build All Projects
        run: npm run build:ci

  # TODO: Figure out how to get github pages deployment to work.
  # Currently the GitHub Pages deployment throws an error: "Artifact
  # could not be deployed. Please ensure the content does not contain
  # any hard links, symlinks and total size is less than 10GB."
  # For the time being this will be deployed to Netlify. In the future
  # we will switch this to use GH Pages - @russell.green
  #
  #     - name: Fix permissions
  #       run: |
  #         chmod -c -R +rX "dist/apps/demo/browser/" | while read line; do
  #           echo "::warning title=Invalid file permissions automatically fixed::$line"
  #         done

  #     - name: Archive build
  #       if: success() && github.event_name != 'pull_request'
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: github-pages
  #         path: dist/apps/demo/browser

  # deploy:
  #   if: github.event_name != 'pull_request'
  #   runs-on: ubuntu-latest
  #   needs: build
  #   permissions:
  #     pages: write
  #     id-token: write
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   steps:
  #     - name: Setup Pages
  #       uses: actions/configure-pages@v4
  #     - name: Deploy to GitHub Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v4
