name: Test build and publish library
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  Test-and-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint:ci

      - name: Test
        run: npm run test:ci

      - name: Build All Projects
        run: npm run build:ci

      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
